// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwiMxLZ3TAbt8RBttR2TME7DIdjMw2AXI',
    appId: '1:292905878675:android:e13a38bc23f1387ad2b966',
    messagingSenderId: '292905878675',
    projectId: 'tamweel-misr',
    storageBucket: 'tamweel-misr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJjvh5EE9XItzwvj_x6-qgxOJhJb4Ui3Y',
    appId: '1:292905878675:ios:33cf380162f29350d2b966',
    messagingSenderId: '292905878675',
    projectId: 'tamweel-misr',
    storageBucket: 'tamweel-misr.appspot.com',
    androidClientId: '292905878675-b3tq7ja4ca33ngij085v3lo7danka1id.apps.googleusercontent.com',
    iosClientId: '292905878675-uq5rvgtmh7ivmd2kilj7k5uodt3o44ae.apps.googleusercontent.com',
    iosBundleId: 'com.example.tamweel',
  );
}
